---
# Copyright 2016, Catalyst IT Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Add zaqar apache WSGI script
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ zaqar_system_user_name }}"
    group: "{{ zaqar_system_group_name }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: "zaqar-wsgi.py.j2", dest: "/var/www/cgi-bin/zaqar/app", mode: "0755" }
  notify:
    - Restart Apache
  tags:
    - zaqar-httpd

- name: Add zaqar apache configuration file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
  with_items:
    - { src: "zaqar-httpd.conf.j2", dest: "/etc/apache2/sites-available/zaqar-httpd.conf" }
  notify:
    - Restart Apache
  tags:
    - zaqar-httpd

- name: Disable default apache site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: "absent"
  notify:
    - Restart Apache
  tags:
    - zaqar-httpd

- name: Enabled zaqar vhost
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
    - { src: "/etc/apache2/sites-available/zaqar-httpd.conf", dest: "/etc/apache2/sites-enabled/zaqar-httpd.conf", state: "link" }
  notify:
    - Restart Apache
  tags:
    - zaqar-httpd

- name: Ensure Apache ServerName
  lineinfile:
    dest: "/etc/apache2/apache2.conf"
    line: "ServerName {{ inventory_hostname }}"
  notify:
    - Restart Apache
  tags:
    - zaqar-httpd

- name: Ensure Apache ServerTokens
  lineinfile:
    dest: "/etc/apache2/conf-available/security.conf"
    regexp: '^ServerTokens'
    line: "ServerTokens Prod"
  notify:
    - Restart Apache
  tags:
    - zaqar-httpd

- name: Ensure Apache ServerSignature
  lineinfile:
    dest: "/etc/apache2/conf-available/security.conf"
    regexp: '^ServerSignature'
    line: "ServerSignature Off"
  notify:
    - Restart Apache
  tags:
    - zaqar-httpd
